<?php

namespace App\Http\Requests;

use App\Boundaries\PostInputBoundary;
use App\Models\User;
use Illuminate\Foundation\Http\FormRequest;

class WritePostRequest extends FormRequest implements PostInputBoundary
{
    public function getUser():User
    {
        return  parent::user(); // TODO: Change the autogenerated stub
    }

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return false;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
        ];
    }


}
